export type ProductCategory = "flagship" | "open-source" | "research";
export type ProductVisual = "capture" | "learnloop" | "whitespace" | "aethel";

export type Product = {
  slug: string; index: string; name: string; kicker: string; category: ProductCategory; status: string; color: string;
  oneLiner: string; description: string; tags: string[]; metric: string; metricLabel: string; visual: ProductVisual;
  problem: string; approach: string; bullets: string[]; github?: string;
};

export const categories: { id: ProductCategory; label: string; short: string; count: string }[] = [
  { id: "flagship", label: "Flagship products", short: "Products", count: "02" },
  { id: "open-source", label: "Open source", short: "Open source", count: "01" },
  { id: "research", label: "Research concepts", short: "Research", count: "13" },
];

const base = (data: Partial<Product> & Pick<Product, "slug" | "name" | "oneLiner" | "kicker" | "category" | "status" | "color" | "description" | "tags">): Product => ({
  index: "", visual: "aethel", metric: "—", metricLabel: "early signal", problem: "The useful thing is buried beneath too many steps, surfaces, and decisions.", approach: "Build the smallest calm layer that makes the useful part feel immediate.", bullets: ["One clear job", "A quieter interface", "Designed to compound"], ...data,
});

const researchConcepts: Product[] = [
  ["trendculture", "TrendCulture", "A swipeable signal feed for understanding what culture is becoming."], ["driftboard", "Driftboard", "A spatial canvas where saved ideas cluster into themes over time."], ["afterthought", "Afterthought", "A voice journal that returns a weekly reflection, not a recording."], ["quietboard", "Quietboard", "A daily personal dashboard that redraws itself around what matters."], ["marginalia", "Marginalia", "A searchable commonplace book built around re-reading your highlights."], ["nearby-log", "Nearby Log", "A private map and timeline made from one-line check-ins."], ["standing-notes", "Standing Notes", "Meeting recordings distilled into decisions, actions, and open questions."], ["signalhouse", "Signalhouse", "A severity-aware alert hub for the signals you choose to watch."], ["bundle", "Bundle", "A personal newspaper generated from your reading list each morning."], ["codewell", "Codewell", "A browsable, searchable library for the code you keep reusing."], ["blitz-v5", "Blitz V5", "An AI personal operating system with memory, voice, and proactive assistance."], ["zen-ai", "Zen AI", "A minimalist phone launcher that puts your own assistant in the UI."]
].map(([slug, name, oneLiner], i) => base({ slug, name, oneLiner, index: String(i + 5).padStart(2, "0"), kicker: "A Quiet Studio research concept.", category: "research", status: "Research concept", color: i % 3 === 0 ? "orange" : "cream", description: `${oneLiner} This is an active Quiet Studio concept exploring how software can become more useful by becoming less demanding.`, tags: ["Research concept", "Effortless systems", "Working notes"], metric: "R&D", metricLabel: "current stage", approach: `We are exploring the smallest version of ${name} that can make its core promise feel obvious.`, bullets: ["A distinct point of view", "A calm, focused interaction", "Open questions documented in public"] }));

export const products: Product[] = [
  { index: "01", slug: "capture", name: "Capture", kicker: "Thought, without the tax.", category: "flagship", status: "Private beta", color: "orange", oneLiner: "The quiet layer between having an idea and losing it.", description: "Capture turns scattered thoughts into a useful, searchable system before they disappear. Built for people who think in fragments and build in public.", tags: ["AI-native", "Personal systems", "Private beta"], metric: "3.2s", metricLabel: "from thought to saved", visual: "capture", problem: "Your best thinking happens at the wrong time, in the wrong app, with just enough friction to make it disappear.", approach: "Capture treats the first moment as sacred. Speak, type, or drop a thought in. The system handles the organizing later.", bullets: ["One gesture to capture anything", "AI organizes without changing your voice", "A calm, local-first memory for your work"] },
  { index: "02", slug: "learnloop", name: "LearnLoop", kicker: "Learning, with less ceremony.", category: "flagship", status: "In the lab", color: "cream", oneLiner: "A frictionless loop for turning curiosity into durable understanding.", description: "LearnLoop compresses the distance between finding something interesting and actually knowing it. Small prompts, tight feedback, no productivity theatre.", tags: ["Learning systems", "Adaptive AI", "Concept maps"], metric: "17m", metricLabel: "to first useful loop", visual: "learnloop", problem: "The internet gives you infinite things to read. It does not give you a way to make them yours.", approach: "LearnLoop makes learning feel like a conversation with the material—short, adaptive, and connected to what you already know.", bullets: ["Turn any source into a living loop", "Recall-first prompts that adapt to you", "See your understanding compound"] },
  { index: "03", slug: "zen-ai", name: "Zen AI", kicker: "Serene, local-first AI system layer.", category: "open-source", status: "Open source", color: "orange", oneLiner: "A serene, local-first open source AI engine for effortless workflows.", description: "Zen AI is an opinionated, local-first open source AI system designed to keep intelligence calm, fast, and entirely on-device.", tags: ["Open source", "Local AI", "MIT license"], metric: "0.2ms", metricLabel: "local inference latency", visual: "aethel", problem: "Cloud AI systems introduce network latency, telemetry bloat, and privacy concerns for daily workflows.", approach: "Zen AI puts a lightweight local-first model layer directly into your environment with zero latency.", bullets: ["Local-first intelligence without telemetry", "Zero-latency intent parsing", "MIT licensed open source code"], github: "https://github.com/quiet-studio/zen-ai" },
  { index: "04", slug: "aethel", name: "Aethel", kicker: "Researching the edge of effortless.", category: "research", status: "Exploring", color: "orange", oneLiner: "A research thread on AI systems that feel less like software and more like reflex.", description: "Aethel is where Quiet Studio tests the boundary: how can intelligent systems become more capable while asking less of the people using them?", tags: ["AI research", "Human-computer interaction", "Working notes"], metric: "∞", metricLabel: "questions worth following", visual: "aethel", problem: "The most powerful tools still make people learn their language before they can get anything done.", approach: "Aethel explores ambient interfaces, intent-shaped systems, and models that know when to act—and when to leave you alone.", bullets: ["Prototype the invisible parts of interaction", "Publish the useful failures", "Move capability closer to instinct"] },
  ...researchConcepts,
];

export function getProduct(slug: string) { return products.find((product) => product.slug === slug); }
export function getCategoryLabel(category: ProductCategory) { return categories.find((item) => item.id === category)?.label ?? category; }
